name: Release Beta

on:
  push:
    tags:
      - "v*-beta*"

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: beta-release

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install deps
        run: pnpm install

      - name: Builds
        run: pnpm build

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: pnpm publish --publish-branch beta-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
